DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS film_genres CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS mpa_rating CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS review_likes CASCADE;
DROP TABLE IF EXISTS directors CASCADE;
DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE IF NOT EXISTS mpa_rating (
     id BIGINT PRIMARY KEY AUTO_INCREMENT,
     name_mpa VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS directors (
     id BIGINT PRIMARY KEY AUTO_INCREMENT,
     name VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
     id BIGINT PRIMARY KEY AUTO_INCREMENT,
     name_film VARCHAR(100) NOT NULL,
     description VARCHAR(2000) NOT NULL,
     release_date DATE NOT NULL,
     duration INT NOT NULL CHECK (duration > 0),
     mpa_id BIGINT NOT NULL,
     FOREIGN KEY (mpa_id) REFERENCES mpa_rating(id)
     );

CREATE TABLE IF NOT EXISTS film_directors (
     idFilm BIGINT,
     idDirector BIGINT,
     PRIMARY KEY (idFilm, idDirector),
     FOREIGN KEY (idFilm) REFERENCES films(id) ON DELETE CASCADE,
     FOREIGN Key (idDirector) REFERENCES directors(id) ON DELETE CASCADE
     );

CREATE TABLE IF NOT EXISTS genres (
     id BIGINT PRIMARY KEY AUTO_INCREMENT,
     name VARCHAR(100) NOT NULL
     );

CREATE TABLE IF NOT EXISTS film_genres (
     film_id BIGINT,
     genre_id BIGINT,
     PRIMARY KEY (film_id, genre_id),
     FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
     FOREIGN Key (genre_id) REFERENCES genres(id) ON DELETE CASCADE
     );

CREATE TABLE IF NOT EXISTS users (
     id BIGINT PRIMARY KEY AUTO_INCREMENT,
     email VARCHAR(255) NOT NULL UNIQUE,
     login VARCHAR(100) NOT NULL,
     name VARCHAR(100),
     birthday DATE NOT NULL
     );

CREATE TABLE IF NOT EXISTS likes (
     film_id BIGINT,
     user_id BIGINT,
     PRIMARY KEY (film_id, user_id),
     FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
     FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
     );

 CREATE TABLE IF NOT EXISTS friends (
      user_id BIGINT,
      user_friends_id BIGINT,
      PRIMARY KEY (user_id, user_friends_id),
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (user_friends_id) REFERENCES users(id) ON DELETE CASCADE
      );

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR NOT NULL,
    isPositive boolean NOT NULL,
    user_id BIGINT,
    film_id BIGINT,
    useful INTEGER DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review_likes (
    review_id BIGINT,
    user_id BIGINT,
    like_type VARCHAR NOT NULL,
    PRIMARY KEY (review_id, user_id),
    FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS events (
    id LONG GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL,
    event_type varchar NOT NULL,
    operation varchar NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    time_created timestamp NOT NULL
);