DROP TABLE IF EXISTS FEED_EVENTS CASCADE;
DROP TABLE IF EXISTS Reviews CASCADE;
DROP TABLE IF EXISTS Films CASCADE;
DROP TABLE IF EXISTS Genres CASCADE;
DROP TABLE IF EXISTS FilmGenres CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Friends CASCADE;
DROP TABLE IF EXISTS Likes CASCADE;
DROP TABLE IF EXISTS Mpa_rating CASCADE;

CREATE TABLE IF NOT EXISTS Mpa_rating (
    idMpa BIGINT PRIMARY KEY AUTO_INCREMENT,
    nameMpa VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Films (
    idFilm BIGINT PRIMARY KEY AUTO_INCREMENT,
    nameFilm VARCHAR(100) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    releaseDate DATE NOT NULL,
    duration INT NOT NULL CHECK (duration > 0),
    idMpa BIGINT NOT NULL,
    FOREIGN KEY (idMpa) REFERENCES Mpa_rating(idMpa)
);

CREATE TABLE IF NOT EXISTS Genres (
    idGenre BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FilmGenres (
    idFilm BIGINT,
    idGenre BIGINT,
    PRIMARY KEY (idFilm, idGenre),
    FOREIGN KEY (idFilm) REFERENCES Films(idFilm) ON DELETE CASCADE,
    FOREIGN KEY (idGenre) REFERENCES Genres(idGenre) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Users (
    idUser BIGINT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(100) NOT NULL,
    name VARCHAR(100),
    birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Likes (
    idFilm BIGINT,
    idUser BIGINT,
    PRIMARY KEY (idFilm, idUser),
    FOREIGN KEY (idFilm) REFERENCES Films(idFilm) ON DELETE CASCADE,
    FOREIGN KEY (idUser) REFERENCES Users(idUser) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Friends (
    idUser BIGINT,
    idUserFriends BIGINT,
    PRIMARY KEY (idUser, idUserFriends),
    FOREIGN KEY (idUser) REFERENCES Users(idUser) ON DELETE CASCADE,
    FOREIGN KEY (idUserFriends) REFERENCES Users(idUser) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reviews (
    id_review   BIGINT PRIMARY KEY AUTO_INCREMENT,
    content     VARCHAR(1000) NOT NULL,
    is_positive BOOLEAN NOT NULL,
    user_id     BIGINT NOT NULL,
    film_id     BIGINT NOT NULL,
    useful      INT DEFAULT 0,
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES Users(idUser) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_film FOREIGN KEY (film_id) REFERENCES Films(idFilm) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FEED_EVENTS (
    idEvent BIGINT PRIMARY KEY AUTO_INCREMENT,
    ts TIMESTAMP NOT NULL,
    idUser BIGINT NOT NULL,
    eventType VARCHAR(16) NOT NULL,
    operation VARCHAR(16) NOT NULL,
    entityId BIGINT NOT NULL,
    CONSTRAINT fk_feed_user FOREIGN KEY (idUser) REFERENCES Users(idUser) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review_likes (
    review_id   BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    is_positive BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id),
    CONSTRAINT fk_reviewlikes_review FOREIGN KEY (review_id) REFERENCES reviews(id_review) ON DELETE CASCADE,
    CONSTRAINT fk_reviewlikes_user   FOREIGN KEY (user_id)   REFERENCES Users(idUser)   ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_feed_user_ts ON FEED_EVENTS (idUser, ts, idEvent);
